if(ANDROID_ABI)
  ExternalProject_Add(URIPARSER
  PREFIX URIPARSER
  URL ${PROJECT_SOURCE_DIR}/thirdparty/uriparser-0.7.5.tar.bz2
  URL_MD5 4f4349085fe5de33bcae8d0f26649593
  BINARY_DIR ${CMAKE_BINARY_DIR}/URIPARSER/build
  DOWNLOAD_DIR ${DOWNLOAD_LOCATION}
  PATCH_COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_SOURCE_DIR}/cmake/UriParser_cmake_lists_txt ${CMAKE_BINARY_DIR}/URIPARSER/src/URIPARSER/CMakeLists.txt
  CMAKE_CACHE_ARGS
  -DCMAKE_TOOLCHAIN_FILE:STRING=${CMAKE_TOOLCHAIN_FILE}
  -DANDROID_ABI:STRING=${ANDROID_ABI}
  -DANDROID_NDK:STRING=${ANDROID_NDK}
  -DANDROID_NATIVE_API_LEVEL:STRING=${ANDROID_NATIVE_API_LEVEL}
  -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR}
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
  -DCMAKE_DEBUG_POSTFIX:STRING="d" )
else()
  ExternalProject_Add(URIPARSER
    PREFIX URIPARSER
    URL ${PROJECT_SOURCE_DIR}/thirdparty/uriparser-0.7.5.tar.bz2
    URL_MD5 4f4349085fe5de33bcae8d0f26649593
    BINARY_DIR ${CMAKE_BINARY_DIR}/URIPARSER/build
    DOWNLOAD_DIR ${DOWNLOAD_LOCATION}
    PATCH_COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_SOURCE_DIR}/cmake/UriParser_cmake_lists_txt ${CMAKE_BINARY_DIR}/URIPARSER/src/URIPARSER/CMakeLists.txt
    CMAKE_CACHE_ARGS
    -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR}
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -DCMAKE_DEBUG_POSTFIX:STRING=d )
endif()

include_project_vars(URIPARSER "liburiparser")
