if(ANDROID_ABI)
  ExternalProject_Add(ZLIB
    PREFIX ZLIB
    URL "http://zlib.net/zlib1211.zip"
    URL_MD5 16b41357b2cd81bca5e1947238e64465
    BINARY_DIR ${CMAKE_BINARY_DIR}/ZLIB/build
    DOWNLOAD_DIR ${DOWNLOAD_LOCATION}
    CMAKE_CACHE_ARGS
    -DCMAKE_TOOLCHAIN_FILE:STRING=${CMAKE_TOOLCHAIN_FILE}
    -DANDROID_ABI:STRING=${ANDROID_ABI}
    -DANDROID_NDK:STRING=${ANDROID_NDK}
    -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR}
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS})
else()
  ExternalProject_Add(ZLIB
    PREFIX ZLIB
    URL "http://zlib.net/zlib1211.zip"
    URL_MD5 16b41357b2cd81bca5e1947238e64465
    BINARY_DIR ${CMAKE_BINARY_DIR}/ZLIB/build
    DOWNLOAD_DIR ${DOWNLOAD_LOCATION}
    CMAKE_CACHE_ARGS
    -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR}
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS})
endif()

if(MSVC)
  if(BUILD_SHARED_LIBS)
    include_project_vars(ZLIB "zlib")
  else()
    include_project_vars(ZLIB "zlibstatic")
  endif()
else()
  include_project_vars(ZLIB "libz")
endif()
